name: Hourly Meter Logger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "GitHub Action Working"
